### ISSUE TITLE
FR: Add Dependabot for GitHub Actions version updates

### ISSUE THREAD

**Issue by prbzrg** [JuliaCI/PkgTemplates.jl#358]
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates

Something like this:
```yaml
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
```
at `.github/dependabot.yml`
It updates `actions/checkout` and `codecov/codecov-action` that used in `.github/workflows/CI.yml`, for example.
